version: '3'
# when production ready, use this step:
# download and install pg_dump (for postgresql)
# type in the terminal: pg_dump --no-owner -h localhost -p 5432 -U postgres (databasename) > movies.sql
# in case an error installing pg_dump, change the pg_dump command to our sql file name (create_tables.sql)


services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql